services:
  producer:
    container_name: process-config-producer
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      rabbitmq:
        condition: service_healthy    
    ports:
      - "8080:8080"
    env_file:
      - .env
  
  consumer:
    container_name: process-config-consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      rabbitmq:
        condition: service_healthy   
      processdb:
        condition: service_healthy   
    ports:
      - "8081:8080"
    env_file:
      - .env

  configloader:
    container_name: process-config-loader
    build:
      context: .
      dockerfile: Dockerfile.configloader
    depends_on:
      processdb:
        condition: service_healthy
    ports:
      - "8082:8080"
    env_file:
      - .env
    volumes:
      - ./process_configs:/app/process_configs

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5  

  processdb:
    image: postgres:15.7
    container_name: processdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: processdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d processdb"]
      interval: 1s
      timeout: 1s
      retries: 30
    
  migratedb:
    image: migrate/migrate:v4.17.1
    container_name: migratedb
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "pgx5://user:pass@processdb:5432/processdb", "up" ]
    depends_on:
      processdb:
        condition: service_healthy

volumes:
  pgdata: