// Code generated by counterfeiter. DO NOT EDIT.
package handlerfakes

import (
	"sync"

	"github.com/ggsomnoev/ntt-ds-sap-process-api/internal/model"
	"github.com/ggsomnoev/ntt-ds-sap-process-api/internal/processproducer/handler"
)

type FakeValidator struct {
	ValidateStub        func(model.ProcessDefinition) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 model.ProcessDefinition
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateMandatoryParamsStub        func(model.ProcessDefinition, map[string]string) error
	validateMandatoryParamsMutex       sync.RWMutex
	validateMandatoryParamsArgsForCall []struct {
		arg1 model.ProcessDefinition
		arg2 map[string]string
	}
	validateMandatoryParamsReturns struct {
		result1 error
	}
	validateMandatoryParamsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeValidator) Validate(arg1 model.ProcessDefinition) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 model.ProcessDefinition
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeValidator) ValidateCalls(stub func(model.ProcessDefinition) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeValidator) ValidateArgsForCall(i int) model.ProcessDefinition {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeValidator) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateMandatoryParams(arg1 model.ProcessDefinition, arg2 map[string]string) error {
	fake.validateMandatoryParamsMutex.Lock()
	ret, specificReturn := fake.validateMandatoryParamsReturnsOnCall[len(fake.validateMandatoryParamsArgsForCall)]
	fake.validateMandatoryParamsArgsForCall = append(fake.validateMandatoryParamsArgsForCall, struct {
		arg1 model.ProcessDefinition
		arg2 map[string]string
	}{arg1, arg2})
	stub := fake.ValidateMandatoryParamsStub
	fakeReturns := fake.validateMandatoryParamsReturns
	fake.recordInvocation("ValidateMandatoryParams", []interface{}{arg1, arg2})
	fake.validateMandatoryParamsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeValidator) ValidateMandatoryParamsCallCount() int {
	fake.validateMandatoryParamsMutex.RLock()
	defer fake.validateMandatoryParamsMutex.RUnlock()
	return len(fake.validateMandatoryParamsArgsForCall)
}

func (fake *FakeValidator) ValidateMandatoryParamsCalls(stub func(model.ProcessDefinition, map[string]string) error) {
	fake.validateMandatoryParamsMutex.Lock()
	defer fake.validateMandatoryParamsMutex.Unlock()
	fake.ValidateMandatoryParamsStub = stub
}

func (fake *FakeValidator) ValidateMandatoryParamsArgsForCall(i int) (model.ProcessDefinition, map[string]string) {
	fake.validateMandatoryParamsMutex.RLock()
	defer fake.validateMandatoryParamsMutex.RUnlock()
	argsForCall := fake.validateMandatoryParamsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeValidator) ValidateMandatoryParamsReturns(result1 error) {
	fake.validateMandatoryParamsMutex.Lock()
	defer fake.validateMandatoryParamsMutex.Unlock()
	fake.ValidateMandatoryParamsStub = nil
	fake.validateMandatoryParamsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) ValidateMandatoryParamsReturnsOnCall(i int, result1 error) {
	fake.validateMandatoryParamsMutex.Lock()
	defer fake.validateMandatoryParamsMutex.Unlock()
	fake.ValidateMandatoryParamsStub = nil
	if fake.validateMandatoryParamsReturnsOnCall == nil {
		fake.validateMandatoryParamsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateMandatoryParamsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	fake.validateMandatoryParamsMutex.RLock()
	defer fake.validateMandatoryParamsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.Validator = new(FakeValidator)
