// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/ggsomnoev/ntt-ds-sap-process-api/internal/model"
	"github.com/ggsomnoev/ntt-ds-sap-process-api/internal/processloader/service"
)

type FakeReader struct {
	ParseConfigFileStub        func(string) (model.ProcessDefinition, error)
	parseConfigFileMutex       sync.RWMutex
	parseConfigFileArgsForCall []struct {
		arg1 string
	}
	parseConfigFileReturns struct {
		result1 model.ProcessDefinition
		result2 error
	}
	parseConfigFileReturnsOnCall map[int]struct {
		result1 model.ProcessDefinition
		result2 error
	}
	ReadYAMLFilesStub        func() ([]string, error)
	readYAMLFilesMutex       sync.RWMutex
	readYAMLFilesArgsForCall []struct {
	}
	readYAMLFilesReturns struct {
		result1 []string
		result2 error
	}
	readYAMLFilesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeReader) ParseConfigFile(arg1 string) (model.ProcessDefinition, error) {
	fake.parseConfigFileMutex.Lock()
	ret, specificReturn := fake.parseConfigFileReturnsOnCall[len(fake.parseConfigFileArgsForCall)]
	fake.parseConfigFileArgsForCall = append(fake.parseConfigFileArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ParseConfigFileStub
	fakeReturns := fake.parseConfigFileReturns
	fake.recordInvocation("ParseConfigFile", []interface{}{arg1})
	fake.parseConfigFileMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeReader) ParseConfigFileCallCount() int {
	fake.parseConfigFileMutex.RLock()
	defer fake.parseConfigFileMutex.RUnlock()
	return len(fake.parseConfigFileArgsForCall)
}

func (fake *FakeReader) ParseConfigFileCalls(stub func(string) (model.ProcessDefinition, error)) {
	fake.parseConfigFileMutex.Lock()
	defer fake.parseConfigFileMutex.Unlock()
	fake.ParseConfigFileStub = stub
}

func (fake *FakeReader) ParseConfigFileArgsForCall(i int) string {
	fake.parseConfigFileMutex.RLock()
	defer fake.parseConfigFileMutex.RUnlock()
	argsForCall := fake.parseConfigFileArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeReader) ParseConfigFileReturns(result1 model.ProcessDefinition, result2 error) {
	fake.parseConfigFileMutex.Lock()
	defer fake.parseConfigFileMutex.Unlock()
	fake.ParseConfigFileStub = nil
	fake.parseConfigFileReturns = struct {
		result1 model.ProcessDefinition
		result2 error
	}{result1, result2}
}

func (fake *FakeReader) ParseConfigFileReturnsOnCall(i int, result1 model.ProcessDefinition, result2 error) {
	fake.parseConfigFileMutex.Lock()
	defer fake.parseConfigFileMutex.Unlock()
	fake.ParseConfigFileStub = nil
	if fake.parseConfigFileReturnsOnCall == nil {
		fake.parseConfigFileReturnsOnCall = make(map[int]struct {
			result1 model.ProcessDefinition
			result2 error
		})
	}
	fake.parseConfigFileReturnsOnCall[i] = struct {
		result1 model.ProcessDefinition
		result2 error
	}{result1, result2}
}

func (fake *FakeReader) ReadYAMLFiles() ([]string, error) {
	fake.readYAMLFilesMutex.Lock()
	ret, specificReturn := fake.readYAMLFilesReturnsOnCall[len(fake.readYAMLFilesArgsForCall)]
	fake.readYAMLFilesArgsForCall = append(fake.readYAMLFilesArgsForCall, struct {
	}{})
	stub := fake.ReadYAMLFilesStub
	fakeReturns := fake.readYAMLFilesReturns
	fake.recordInvocation("ReadYAMLFiles", []interface{}{})
	fake.readYAMLFilesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeReader) ReadYAMLFilesCallCount() int {
	fake.readYAMLFilesMutex.RLock()
	defer fake.readYAMLFilesMutex.RUnlock()
	return len(fake.readYAMLFilesArgsForCall)
}

func (fake *FakeReader) ReadYAMLFilesCalls(stub func() ([]string, error)) {
	fake.readYAMLFilesMutex.Lock()
	defer fake.readYAMLFilesMutex.Unlock()
	fake.ReadYAMLFilesStub = stub
}

func (fake *FakeReader) ReadYAMLFilesReturns(result1 []string, result2 error) {
	fake.readYAMLFilesMutex.Lock()
	defer fake.readYAMLFilesMutex.Unlock()
	fake.ReadYAMLFilesStub = nil
	fake.readYAMLFilesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeReader) ReadYAMLFilesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.readYAMLFilesMutex.Lock()
	defer fake.readYAMLFilesMutex.Unlock()
	fake.ReadYAMLFilesStub = nil
	if fake.readYAMLFilesReturnsOnCall == nil {
		fake.readYAMLFilesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.readYAMLFilesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseConfigFileMutex.RLock()
	defer fake.parseConfigFileMutex.RUnlock()
	fake.readYAMLFilesMutex.RLock()
	defer fake.readYAMLFilesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Reader = new(FakeReader)
